server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka